### ISSUE TITLE
Add Serie in the Book object

### ISSUE THREAD

**Issue by BenjiDum** [manchaques/micose-backend#1]
We need to improve the data Model for Book object in order to add the Serie.

It will allow us to query the database for data like : 
- Give me all the Batman Comics
- Give me all the Superman Comics that belongs to Pierre

**Comment by PierrePIRONIN** [comment]
What about manage series and others "complementary" informations with tags ?

**Comment by BenjiDum** [comment]
Implemented on 'add_tag' branch
Works for the json view for the book object, not the ExAdmin one for now

**Comment by BenjiDum** [comment]
branch merged on the master
